//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileConverter.Hashes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HashResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HashResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileConverter.Hashes.HashResources", typeof(HashResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## LM2 ##
        ///
        ///chaserghost.config
        ///creeperbossghost.config
        ///creeperghost.config
        ///.nlg
        ///00.nlg
        ///02.nlg
        ///03.nlg
        ///04.nlg
        ///05.nlg
        ///06.nlg
        ///06a.nlg
        ///06d.nlg
        ///07.nlg
        ///1
        ///1.nlg
        ///2.nlg
        ///3.nlg
        ///nisasset-art/feghosts/boo.nlg/boo
        ///AnimatedEntity.script
        ///Cameras.script
        ///Hard.script
        ///Easy.script
        ///SuperEasy.script
        ///Medium.script
        ///0.script
        ///1.script
        ///2.script
        ///3.script
        ///art/textures/global/checkers.tga
        ///art/characters/luigicleaner/textures/luigi.tga
        ///art/characters/luigicleaner/textures/poltergust.tga
        ///art/characters/luigicleaner/textures/luigi_blue/luigi_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileNames {
            get {
                return ResourceManager.GetString("FileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## LM3 ##
        ///aapostprocess
        ///aopostprocess
        ///atmosphericfog
        ///balloon_scary
        ///base_blended_metal
        ///base_blinking
        ///base_boss_eyes
        ///base_candle
        ///base_crosssection_01
        ///base_emissive
        ///base_emissive_unlit
        ///base_enviroment_cutout
        ///base_environment
        ///base_environment_3tint
        ///base_environment_carpets
        ///base_environment_detailn
        ///base_environment_dusty
        ///base_environment_fogless_01
        ///base_environment_grunge
        ///base_environment_grunge_detailn
        ///base_environment_metalmap_detailn
        ///base_environment_metalmap_wear
        ///base_environment_paintings
        ///base_environment_p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaterialNames {
            get {
                return ResourceManager.GetString("MaterialNames", resourceCulture);
            }
        }
    }
}
